# Generated by Django 5.0.6 on 2024-07-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('image', models.CharField(max_length=200, verbose_name='Image')),
                ('category', models.CharField(choices=[('drinks', 'Drinks'), ('meat', 'Meat'), ('frozen', 'Frozen'), ('food', 'Food'), ('drinks', 'Drinks')], default='Other', max_length=200, verbose_name='Category')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
    ]
