# Generated by Django 5.0.6 on 2024-07-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_count_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInBasket',
            new_name='ShoppingCart',
        ),
    ]
