# Generated by Django 5.0.6 on 2024-07-20 13:00

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_productinbasket_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[shop.validators.more_than_zero], verbose_name='Total'),
        ),
    ]
