# Generated by Django 5.0.6 on 2024-07-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shoppingcart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(verbose_name='User')),
                ('phone', models.CharField(verbose_name='Phone')),
                ('Address', models.CharField(verbose_name='Address')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('products', models.ManyToManyField(related_name='orders', to='shop.product', verbose_name='Products')),
            ],
        ),
    ]
