# Generated by Django 5.0.6 on 2024-07-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
    ]
