# Generated by Django 5.0.6 on 2024-07-21 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_deleted',
            field=models.BooleanField(default='False', verbose_name='Is Deleted'),
        ),
        migrations.CreateModel(
            name='ShoppingCartForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default='False', verbose_name='Is Deleted')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.shoppingcart', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='shop.ShoppingCartForOrder', to='shop.shoppingcart', verbose_name='Products'),
        ),
    ]
